### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by jisaf** [jondot/hygen#101]
Hi team,

Let me start by saying I suspect this is because my environment is locked to Node 6.9.1 (and I can't change it), but figured I would post in case there is something I can do to work around this issue.

When running `hygen init self` I get the following warning:

`
Loaded templates: <...>\node_modules\hygen\src\templates
SyntaxError: Unexpected token ...
`

My guess is that it's because Node pre v8 doesn't handle `...` spread operators, but could it be something else that I'm missing, and is there a possible work around you might be able to think of?

Many thanks!

**Comment by jondot** [comment]
Hi, you're right. Unfortunately we don't support older Node versions.
If you really want to use Hygen and not upgrade Node, you still have a few options:

1. If you're on OSX just `brew tap jondot/tap && brew install hygen`
2. Use one of the [releases](https://github.com/jondot/hygen/releases). It contains hygen bundled with a recent Node version. So for all intents and purposes it's just a binary that works with no dependencies
3. Clone the repo, and configure babel to compile to support as low a Node process as you want. It should be possible; however this will be something that you will have to maintain since the original idea of Hygen supporting only recent Node is speed.

Closing up but feel free to reopen if you need more help.

**Comment by jisaf** [comment]
Thanks Jon, figured that might be the case. I appreciate the work arounds and will see what I can pull off given our security regime.

Many thanks!

**Comment by jondot** [comment]
Sure thing. While I don't know your security requirements, but from my experience sometimes locking down onto an old version is actually a security issue (because exploits get discovered as time moves on, and so being locked on a single version is like being a sitting duck).

If you need any help with that, as I have extensive security experience, I would be happy to help.
