### ISSUE TITLE
Not generating all template files

### ISSUE THREAD

**Issue by masiamj** [jondot/hygen#121]
Hi @jondot - awesome project! I love using Hygen and it's been a great tool for my team's workflow.

Right now, I'm just running into an issue I haven't experienced before.

In a new prompt generator called `module`, I have 7 template files. But when I run `hygen module with-prompt`, the only resulting files being generated are the `index.js` and `model.js` files.

Here's the directory structure for reference: 
![image](https://user-images.githubusercontent.com/7084914/58766847-4ea42d80-8549-11e9-9516-eee7d8584547.png)

And the repo is available here: https://github.com/masiamj/apollo-server-express-example

Any input you have would be greatly appreciated. Thanks!

**Comment by jondot** [comment]
Thanks for providing a repo for reproducing, this makes it easier and even -- dare I say -- exciting to work on :)
I'll check it out within the day

**Comment by jondot** [comment]
Hi, if you look very deeply (I must admit it tricked me too!), you have:

```
---
to:  ..
--
```

Note only two dashes `--` in closing frontmatter instead of three `---`
:)

Fixing to three, on my end fixes the problem. I'll go ahead and close this one, but feel free to reopen if you feel something is still strange.

Thanks for the feedback, please don't hesitate to report issues :)

**Comment by masiamj** [comment]
Thanks @jondot  for your quick response and great find!
