### ISSUE TITLE
Is there a way to check hygen version? 

### ISSUE THREAD

**Issue by rantav** [jondot/hygen#127]
I'm looking for something like `hygen --version`, tried different variations (e.g. `-v`, `-h`), none worked.

**Comment by jondot** [comment]
Sounds good. I think what we'll do is have it print the version as its banner when you run an empty `$ hygen`

**Comment by grantbowering** [comment]
@jondot I recently went back to an older project to refactor some templates, but found my changes didn't work, because the package.json had a 2.x version of hygen in it (which doesn't recurse arbitrary subdirs for templates).  But using the generator doesn't crash, it just doesn't discover all the template files, so to the user it looks like it worked even though it only wrote a fraction of the files...  
I'm concerned that if other devs on the project don't happen to run npm install before using these updates, they won't realize the template didn't do all the work.  
I would love to be able to put a statement in my `index.js` file, like inside the prompt function, that checks the hygen version and outputs a message or throws an error or something if the version is too low for the template...
Is there something that I can `require` that would give me access to the hygen version so I can do that?  :)

**Comment by jondot** [comment]
you should be able to have `VERSION`, exported in next version (v6.x)
