### ISSUE TITLE
Install and reuse generators across projects in a predictable way?

### ISSUE THREAD

**Issue by robertherber** [jondot/hygen#14]
Is there a suggested way to install collections of generators? I feel this would be the ideal way to reuse generators across projects/teams/organizations in a predictable way. If there is not a way currently - this is a feature request! :)

From what I understand there are two main ways now:
* Add them - more or less manually - to `_templates` in the current project. This is great for project-specific projects - but not ideal for generators you want to reuse.
* Add them to the folder `HYGEN_TMPLS` points to. This is one way to share templates - but it lacks a good way to install versioned collections of packages across a team for example.

**Comment by agung-wete** [comment]
right now i'm exploring [SAO](https://github.com/saojs/sao)
From Readme

> SAO is compatible with:
> 
> Regular git repo (simply download it)
> SAO template as git repo
> SAO template as npm package
> SAO template in local folder

so we can add generator files from various option

**Comment by robertherber** [comment]
Looks really cool! Will check it out. Thanks @agung-wete!

**Comment by jondot** [comment]
@robertherber yes, there's a way. I'm working on `hygen-add`. It's ready but has no documentation or publication yet because I'm still thinking about how it feels to work with it.
This might be a great way to get some feedback from you!

Here's how to use `hygen-add`:

1. Build an npm package with the prefix `hygen-`, like you're used to, that has a `_templates` folder in it, and push it to the npm registry as usual. For example `hygen-coolstuff`.
2. Install `hygen-add` globally or project local
3. run `hygen-add coolstuff` and it'll add the templates as you want!

As mentioned I'm still dogfooding on it, so any feedback is really appreciated. If you feel it's great I can go ahead and publicly announce `hygen-add` (and add the needed docs)

**Comment by agung-wete** [comment]
@jondot great, please consider support for git repo

**Comment by jondot** [comment]
For sure! Currently hygen-add works by embedding Yarn so it inherits all of Yarns capabilities (including yarn’s ability to work with Git). I’m evaluating the experience of how it plays out giving it a git repo directly. Will update in a couple days!

**Comment by robertherber** [comment]
@jondot @agung-wete After having a look at [SAO](https://github.com/saojs/sao) I'm thinking Hygen and SAO tries to accomplish the same things. Is it not better to join forces around one ecosystem? Or is there something that you feel is fundamentally different @jondot? What are your thoughts?

**Comment by jondot** [comment]
I wasn’t aware of sao before, I guess because I’m more of a React person so I tried to give it the best of my review right now.

In general hygen doesn’t try to be a project generator - it was built to be a side kick, to accompany you with all of your boilerplate work through out the entire life of a project. It’s my impression that sao wants to be a better yeoman, and help scaffold a project.

In any case hygen is very young still so I would want it to grow more and find its direction rather than go into the task of merging it into something that we’re not yet sure if is the same and has the same goal and vision

**Comment by jondot** [comment]
Hi guys,
I'm happy to announce `hygen-add` (see [Hygen Packages](www.hygen.io/packages)) now supports adding packages (parallel to npm modules) as described. It also supports Git repos.

I'll be closing this issue but feel free to reopen to discuss things that are still missing.
