### ISSUE TITLE
Support Binary Files

### ISSUE THREAD

**Issue by vibrantrida** [jondot/hygen#147]
I'm using hygen to generate projects and I noticed that binary files aren't supported yet, it would be great to have them copied over to the generated project.

**Comment by jondot** [comment]
Did you try the shell operator with a regular `cp` command?

**Comment by vibrantrida** [comment]
I tried but before `hygen` could execute the shell action it terminates with an error showing that it is reading the binary file as a template, attempting to render the file when it shouldn't.

Here's what my template looks like:
![image](https://user-images.githubusercontent.com/30256166/65315256-5821d600-dbca-11e9-88f8-de5ff109866c.png)

The highlighted `PLAYPAL.pal` is the binary file, running my generator shows that `hygen` is attempting to render this file:
```
Error: Could not find matching close tag for "<%".
```
Searching for `<%` led me to a line inside `PLAYPAL.pal`:
![image](https://user-images.githubusercontent.com/30256166/65315507-ccf51000-dbca-11e9-82cb-3553151cce75.png)

**Comment by jondot** [comment]
Interesting. this means hygen needs to support some kind of ignores.
I'm thinking in order to help you with this, to implement one of the following, to ignore these:

1. folders/files that start with a dot (`.`) are ignored
2. folders/files that are named `assets`
3. folders/files that start with `__`

What do you think? any other ideas maybe?

**Comment by vibrantrida** [comment]
The dot prefix and `assets` directory sounds good! but perhaps instead of prefixing dots, hygen will have something akin to `.gitingore` that will act as a list of files and/or templates to be ignored altogether.

**Comment by jondot** [comment]
Fantastic idea. Something like .spectralignore, which is generator specific or simply relevant for all files if placed at the root of .templates.
I'm going to do some research to see how that can be implemented efficiently

**Comment by jondot** [comment]
Should be now supported with a local `.hygenignore` per action.
Note this also helped speed up Hygen by a good margin since I notice we can skip reading metadata OS files such as `.DS_Store`

Thanks for driving this feature!
Please reopen if this is not quite working as you expect

**Comment by nareshbhatia** [comment]
I am not able to make this feature work. I have a [.hygenignore in my repo](https://github.com/nareshbhatia/codegen-eval/blob/main/hygen-generators/_templates/react-app/.hygenignore) and it lists `src/favicon.ico` in it. The idea is that since `favicon.ico` is a binary file, it should be copied to the destination as is. In reality, when I run the generator, the file does not get copied at all.  Try `hygen react-app new my-app`.

Am I using this correctly?

**Comment by samuellawrentz** [comment]
Same issue here, how to make hygen work with image files - Just copy to the destination folder?

**Comment by jagnk** [comment]
I get the same issue. I replicated @nareshbhatia config without the luck. Also tried to cp it to the destination, but hugen shows below error:
cp: network-diagram.jpg: No such file or directory

**Comment by nareshbhatia** [comment]
@jagnk I have moved over to a different code generator since my earlier comment (https://www.code-shaper.dev/) which does not have this issue.
