### ISSUE TITLE
`ts-jest` should be a dev dep

### ISSUE THREAD

**Issue by milesj** [jondot/hygen#166]
As the title states.

**Comment by jondot** [comment]
thanks!

**Comment by bpatram** [comment]
Hi! This issue has been marked closed but ts-jest is still listed as a dependency and not a dev-dependency as it should. This is causing some extra bloat when using Hygen that doesn't need to be. This also causes misleading npm WARNs due to missing peer-dependencies from ts-jest and its dependencies when installing.
