### ISSUE TITLE
Help / Feature requests

### ISSUE THREAD

**Issue by kartik2406** [jondot/hygen#17]
Hi, great work going on here.

I just wanted some help. 
I want to have the following in my generator:
1. Enter how many items? ( or More items?)
2. Enter item details? ( this should be called n times based on value of question 1)

What is the right approach for this.

**Comment by jondot** [comment]
Great question. Generally Hygen is not iterative (meaning, take some parameters, compute, and then take some more parameters, etc.). It needs all of the variables before running the generator engine.

I've been thinking about this and can't see a great solution, however, you should know that `prompt.js` is a normal Javascript file that's being `require`d, so maybe that helps.
Also, anything you can do with Inquirer (https://github.com/SBoudrias/Inquirer.js) is possible, so maybe that will help as well.

Otherwise I'd be happy to see how it went and what solution you took so that we can put it on the FAQ

**Comment by kartik2406** [comment]
Oh okay. Thanks for your help. I will work along these lines and come up with a solution.

**Comment by kartik2406** [comment]
I was thinking about going with this approach. 
https://github.com/SBoudrias/Inquirer.js/blob/master/examples/recursive.js
But this doesn't export array of questions. I tried exporting functions but it doesn't seem to work.
Could you guide me with this?

**Comment by kartik2406** [comment]
One way I could think of is to use inquirer module in prompt.js to ask the first question, then based on the input i will create n copies of 2nd question and add it to exports. Not sure if it's the correct method though.

**Comment by jondot** [comment]
Moved to roadmap, thanks!
