### ISSUE TITLE
v6 Breaking Changes?

### ISSUE THREAD

**Issue by mAAdhaTTah** [jondot/hygen#237]
Hi–just got notice that v6 has been released (yay!). I was looking through the CHANGELOG to see if there were any breaking changes to be aware of & nothing jumped out at me. Were there breaking changes here we should be aware of when upgrading?

**Comment by jondot** [comment]
Hi,
Per usual there shouldn't be any breaking changes, however the major version signifies you should test your use cases. For example, enquirer was a major upgrade which is a dependency of Hygen (enquirer is the prompting library) and since we don't really know if _they_ had any nuanced breaking change we recommend testing + did a major bump.

**Comment by mAAdhaTTah** [comment]
Sounds good, thanks for the insight!
