### ISSUE TITLE
Use multiple templates with same destination

### ISSUE THREAD

**Issue by vaagnavanesyan** [jondot/hygen#328]
I want to make template which would generate reducer and add it to the root reducer. So I've create to template files - first one adds `import` statement to root reducer and the second one adds imported reducer to the array of reducers in the same root reducer's file.

Please refer these two template files:
https://github.com/vaagnavanesyan/generators-demo/blob/master/hygen/_templates/new/entity/inject_reducer_import.ejs.t
https://github.com/vaagnavanesyan/generators-demo/blob/master/hygen/_templates/new/entity/inject_reducer.ejs.t

When I run template generation I found that the only one (first) template were applied. If I would remove that template file - the second one would be applied. Can I somehow apply multiple injections to the same file now? And could you elaborate if my case is bug or not 🙂

**Comment by vaagnavanesyan** [comment]
@jondot could you please clarify this issue?

**Comment by vinnymac** [comment]
@vaagnavanesyan I may be wrong, but I would think this is because you’ve used the same exact `skip_if` in both templates.

Perhaps try making the second templates skip_if more specific, by requiring a comma at the end of the string. This should allow both to run, since the first template doesn’t use a comma at the end of its `skip_if`.

Just my two cents. Hope it helps.

**Comment by jondot** [comment]
@vinnymac is correct. closing because looks like resolved
