### ISSUE TITLE
Should not install globally

### ISSUE THREAD

**Issue by MathRobin** [jondot/hygen#41]
Installing globally is not realy a good practice. Very useful but not a good practice. For exemple, I work on a micro-services architecture at my work. We have a lot of packages depending each on a different version of node and of dependencies. 

From npm@5.2.0, there is npx included in node (available since [july 2017](https://github.com/npm/npm/releases/tag/v5.2.0)) which can run a local package bin as it was install globally.

So for using hygen, I already can do :
```bash
npx hygen ...
```
instead of
```bash
hygen ...
```
Not really more difficult but a better practice

**Comment by jondot** [comment]
@MathRobin take note that the recommended way to install hygen today is via Homebrew (for macOS), because it yields the fastest invoke times.
People may choose that, or if on a different system, may choose to install globally to get the benefit of disk caching and hygen invocation performance.

I know it sounds like premature optimization but one guiding principle with hygen is that it should be a fast user interface and a CLI is a user interface as any. Currently, on my machine it does a 100ms response on `hygen`, which feels super slick.

**Comment by MathRobin** [comment]
I don't work on mac, on classic debian-like distrib,no performance problem notified when using hygen with npx, comparing to global.
Maybe a difference between mac and normal unix/linux system.

**Comment by MathRobin** [comment]
Just for your information,
On local install, using npx with a debian 9 in virtual machine with near average config machine for dev. I get this when :
```shell
time npx hygen component new --name pouet

Loaded templates: _templates
       added: src/app/components/pouet/pouet.component.html
       added: src/app/components/pouet/pouet.component.js
      inject: src/app/app.js
       added: test/unit/components/pouet/pouet.component.spec.js
npx hygen component new --name pouet  0,24s user 0,05s system 88% cpu 0,325 total
```
Seems pretty fast ;)

**Comment by jondot** [comment]
Looks awesome, this means we need to add `npx` as an official getting started method, and to "downgrade" installing globally, as you recommend.
PS. it might be interesting to run the binary (you can download it from this github repo on 'releases') and see how it performs

**Comment by jondot** [comment]
I've pushed a commit (CI should update the docs).
Thanks for bringing this up!!

**Comment by MathRobin** [comment]
Thank you for this great tool!
