### ISSUE TITLE
Discover dynamically index.js path

### ISSUE THREAD

**Issue by Lughino** [jondot/hygen#49]
Hi Dotan,
I'm playing a lot with your module.. :)
I'm trying to find a way to discover the location of the `index.js` when I run a command.
Suppose this case:
I'm in the root of the project, I run the command for creating a new component, I ask the user to specify a path for the component, now depending to the current directory I need to find a way to get the correct path for inject the component into `index.js`.
So:
current directory: `Projects/funnyProject`
I ask the user to insert the path, for example: `src/atoms`
the component will be created in `Projects/funnyProject/src/atoms/ComponentName`
now I need to inject the correct path into the index file `src/index.js`..

Have you some suggestions?
Thanks

**Comment by jondot** [comment]
This is interesting. So you ask the user the target path (you don’t know it beforehand) and then you generate into the path.

At the next step you want to inject that same path somewhere, and you don’t know beforehand what this path is because the user is in charge of inputting it. 

At the first stage - the path was input into a variable right? What if you use that same variable in the following step? (You can do it - variables are shared between all templates)

If you think it is hard to describe this problem or I didn’t get it right - please feel free to make a git repo with the problem you are facing and I will work on it directly. I’ll be happy to fix it for you

**Comment by Lughino** [comment]
Thanks for the help Dotan!
This is the repo https://github.com/Lughino/hygen-test-component.
I wrote a very quick readme, let me know if is enough to understand the goal.

**Comment by jondot** [comment]
Hi Luca, sorry for the late response. I'm running through the example and I think I have a clue at what's wrong. Will update shortly!

**Comment by jondot** [comment]
I'm happy to say the issue is now resolved!

The problem was in Hygen's inject op:

```
path.join(cwd, target)
// join(/Users/foo/bar, /Users/baz) will not do the smart thing with two absolute paths.
```

was replaced with

```
path.resolve(cwd, target)
```

In your project, I have added a helper called `src` which will point to the directory of `.hygen.js` which is the root directory for the project:

```javascript
module.exports = {
  templates: `${__dirname}/_templates`,
  helpers: {
    relative: (from, to) => path.relative(from, to),
    src: ()=> __dirname
  }
};
```

And this is how I use it to build `<root>/src/index.js`

```yaml
---
to: "<%= h.src() %>/src/index.js"
inject: true
```

Finally - thanks for your time - it takes the community to discover requirements I never had, and I really appreciate it!

Grazie! ❤️

**Comment by sandalsoft** [comment]
I had this same problem, and I solved it by dynamically discovering the upstream root path inside a node project.   This lets me run a generator from any directory inside my project and place files inside ```projectRoot/src```, ```projectRoot/test```, etc..  Maybe overkill for your purpose, but figured I'd share in case it helps someone else.  The code is cryptic because I was playing with a functional/no-if-statement style at the time.  If you find value in this, I can clean it up and submit a PR.

```
// get-project-root-dir.js


import fs from 'fs-extra';
import path from 'path';


// Default to typical file/directory names found in root path of Node JS project 
const AnchorFiles = ['package.json', 'node_modules'];


/**
 * 
 * Checks for existence of all filenames in a directory
 * 
 * @param  {String} dir Directory to test for root path
 * @param  {String[]} anchorFiles Array of filenames to check for the existence of
 * @returns {boolean} `true` if all filenames in `anchorFiles[]` exist in the path `dir`, otherwise returns `false`
 */
const dirContainsAllAnchorFiles = (dir, anchorFiles = AnchorFiles) => {
    const anchorList = anchorFiles
        .map((anchor) => {
            return fs.existsSync(path.join(dir, anchor));
        })
        .filter((val) => {
            return val === true;
        });
    return anchorList.length === anchorFiles.length ? true : false;
};


/**
 * 
 * Returns the upstream root path of the current project
 * 
 * @param  {String} dir Directory to start search from.  Defaults to `cwd()`
 * @param  {String[]} anchorFiles Array of filenames to check the existence of.  Defaults to node project files `['package.json', 'node_modules']`
 * @returns {String} Path of the base project directory 
 */
export const getProjectRootDir = ({
    dir = process.cwd(),
    anchorFiles = AnchorFiles
}) => {
    !dir &&
        (() => {
            return false;
        });

    dir === '/' &&
        (() => {
            return '/';
        });

    return dirContainsAllAnchorFiles({ dir, anchorFiles })
        ? dir
        : getProjectRootDir({ dir: path.join(dir, '..') });
};


```

**Comment by jondot** [comment]
Tidying up issues, thanks guys!
