### ISSUE TITLE
`--help` feature request

### ISSUE THREAD

**Issue by shanewholloway** [jondot/hygen#7]
```bash
$ hygen generator new --help
```

I expected to be able to discover from the CLI what command line arguments an action can use. I ended up having to read the action directly to discover that `'name'` and `'action'` were the two arguments.

**Comment by jondot** [comment]
Hi Shane,
Good point. Hygen already supports that to a degree (each action can embed a message, we could do a help action).
Let me spike up a few sketches.

Thanks!

**Comment by jondot** [comment]
How do you feel about this?

```
❯ hygen generator help

Loaded templates: _templates
* help:
generator new --name [NAME] --action [ACTION]
generator with-prompt --name [NAME] --action [ACTION]
```

The awesome part is that `help` is a generator itself (inception!). It just spits out a message without doing anything 😎 

If you're happy with this I'll add it to the built-in generator and document it

**Comment by jondot** [comment]
v1.4.8 is released, and now you have `hygen generator help`.

In addition, here's how to document your own generators that you'll build for yourself:

http://www.hygen.io/generators#documenting-your-generators

Thanks for inspiring this addition!

**Comment by shanewholloway** [comment]
It's certainly in the right direction. It seems a bit strange to ask `generator` for help that covers things "above" it.  Perhaps raise it up a level?  `hygen help {{section}}` and `hygen help {{section}} {{action}}`

**Comment by jondot** [comment]
Yup I see what you mean, but that would generally make `help` a "blessed" keyword. For example, I couldn't ever have a generator named 'help' (say I have a help component I generate often).

So generally it just so happened that the semantics are `hygen noun verb`. But yea, trade offs I guess?

**Comment by EstebanBorai** [comment]
And what about `hygen --help` ? It's the common way to do it.

**Comment by jondot** [comment]
@EstebanBorai definitely correct. So there's two things in hygen that fall under 'convention over configuration' that are here already:

```
$ hygen verb noun  
$ hygen verb noun --arg VAL ...
```
Where `arg` appears _magically_  in your templates.

When I started building and dog-fooding on Hygen more than half a year ago, I played with a few sketches before this, which I ruled out - and eventually I optimized the "UX" for just three concepts:

1. Generator
2. Action
3. Arguments (that become template variables)

It may feel like overthinking but I generally believe CLI UX is as important as any other interface, and there's strong motivation to reduce the number of concepts a user must know (just as in any other UI design).

That meant some perhaps more acceptable patterns like `--help` (probably challenging some POSIX behavior) would be put on the back seat, because it took up a concept. With `--help` in the game, how would I pass CLI variables? maybe `--vars={..json}` or `--var-name` or just blacklist `help` as a variable name? Just sharing the voices in my head from a while ago 😄 

For now it feels `hygen [GENERATOR] help` is a flexible solution, because `help` is just another action. It could print out a short help screen, call another tool for displaying help, a full on documentation - or even open a browser or play a video (as a [shell action](http://www.hygen.io/templates#shell)).

With all of that in mind, I definitely have a last-resort solution, where each template declares variables such as:

```yaml
arguments: foo, bar, baz
```

Or a dedicated help screen like:

```
help: |
   foo!
```

But that would mean blacklisting `--help` and giving the user a less flexible tool to play with to do help.

Phew! long answer but I hope I gave you a peek into what thoughts go in my head trying to balance the tradeoffs.
