### ISSUE TITLE
ejs.t syntax support in intellij

### ISSUE THREAD

**Issue by morriq** [jondot/hygen#87]
Hello,

Webstorm can't highlight syntax correctly. Do I miss some plugin?

**Comment by jondot** [comment]
Hi,
The `t` suffix is just arbitrary. You can pick what ever suffix that matches the content that you are editing. Since I personally use Vim, I don't really care about suffixes and I can instruct Vim to highlight regardless -- so I just pick a random `t` suffix.

Feel free to rename your files to what you want, for example:

```
_templates/
  foobar/
     content/
       package.json    (you don't have to use package.json.t)
       index.js      (you don't have to use index.js.t)
```

I assume that by having the right extension, Intellij will pick up the right syntax.
However note that you have a front-matter so Intellij will see it as an error -- you have to ignore that.
