### ISSUE TITLE
Curly braces on new line and injection

### ISSUE THREAD

**Issue by jaroslaw-weber** [jondot/hygen#91]
I'm currently working on a project where we have separate line for curly braces. For example:
public class Class name
{
...
}
And I would like to inject some fields after the opening bracket but how would I do that? It's not first bracket, I have namespace bracket before that. It would be nice to have full regex functionality for searching injection place.

**Comment by jondot** [comment]
Current functionality is actually accepting regex behind the scenes. I’m not sure the expression is multi line safe though (should be easy to add if not) - did you test and it didn’t work?

**Comment by jaroslaw-weber** [comment]
Yeah, it did not work for multiline, I haven't checked the one line. But the regex was correct (tested with regex101)

**Comment by jondot** [comment]
I've verified the current yaml engine supports custom types. You can use a full Regexp type like so:

```
before: !!js/regexp /You owe/g
```

Specifically note `/You owe/g` where you can use any kind of flag you want.
Closing this issue for now, but please feel free to reopen if relevant :heart:

**Comment by grantbowering** [comment]
I came here to report and seek advice for a similar issue.  
@jondot, maybe you can confirm this, but from what I can see, the reason that multi-line `before` or `after`s don't work is that `injector.js` splits the input by `\n` and then uses lodash `findIndex` to locate the line.  If your regex spans multiple lines, no one line in the array of lines satisfies the regex, so lodash returns -1 and hygen spits the output onto the top of the file.

I have a structure something like this:
```
routes: {
  applesArea: {
    name: "Apples",
    pages: [
      {
        path: "/orchard",
        component: OrchardPage
      },
      {
        path: "/barrel",
        component: BarrelPage
      },
    ]
  },
  orangesArea: {
    name: "Oranges",
    pages: [
      {
        path: "/cheetos",
        component: CheetosPage
      }
    ]
  },
  bananasArea: {
    name: "Bananas",
    pages: [
    ]
  }
}
```
I want to inject new entries into the `pages` array below the appropriate area as part of my add new page generator.  I obviously can't just select for the pages array itself, as every area entry has one, and I need to identify the correct parent.  
This should correctly identify the spot below which the new entry should go:
 
`after: <%= areaName %>Area. {[^}]*pages. \[`

However, what lodash sees when `findIndex` is called is not the above, but: 
```
[0] routes: {
```
```
[1]  applesArea: {
```
```
[2]    name: "Apples",
```
```
[3]    pages: [
```
```
[4]      {
```
...etc.
None of those match the regex.
On one hand, I think it does count as a bug, as it defies the expectations I formed given the documentation's proclamation that the `before` and `after` operators use regex, and it seems like a common use case.  I don't have a quick fix suggestion for fixing their behavior, though, and this could be handled by updating the documentation to make this caveat clear.  
Maybe what's needed in order to address this case is a separate positioning keyword altogether for the frontmatter, for leaving the whole thing as a string and injecting at an absolute character position rather than on the preceeding/proceeding line?  That would provide functionality for inline injections like #96 as well...
@jaroslaw-weber what did you end up doing for this?
