### ISSUE TITLE
Order of execution

### ISSUE THREAD

**Issue by DeX3** [jondot/hygen#93]
Is there a way to define the order of execution for templates and/or shell commands?

e.g.
1. Render a `package.json`
2. Run `npm install` which installs a dependency listed in `package.json`
3. Render a config file
4. Run an executable from the dependency that needs the generated config file

In this case, `1-2` must always be executed before `3-4`, otherwise the dependency wouldn't be installed.

**Comment by jondot** [comment]
Hi,
File should be sorted based on their string value, this is why there is an explicit `to` field -- so that template name can be different than output file name. So for example:

```
0_first_thing.t
1_second_thing.t
```

While on most current file systems this is guaranteed and implicit by `readdir`, I'll make sure to sort explicitly -- so thanks!

**Comment by jondot** [comment]
Done.
Your current hygen should work like I've mentioned above.
I've added an explicit sorting step either way and it should be available in Hygen 2.1.0 -- closing for now, please reopen if needed ❤️

**Comment by DeX3** [comment]
Awesome, love the project btw!

**Comment by jondot** [comment]
❤️
